### ISSUE TITLE
Special characters trip up card

### ISSUE THREAD

**Issue by ioangogo** [custom-cards/podcast-card#2]
I have found a podcast that trips up something, its the triforce podcast: [RSS feed Link](http://yogpod.libsyn.com/rss)

This issue expresses itself by not expanding on click

by the error bellow, it seems to be an issue in the card, probably caused by the exclamation mark in the podcast name 

    https://URL/local/podcast-card.js:2588:38 Uncaught SyntaxError: Failed to execute 'querySelector' on 'DocumentFragment': '#Triforce!' is not a valid selector.

**Comment by ioangogo** [comment]
This will probably just be fixed by encoding the request as a URI

**Comment by iantrich** [comment]
Fixed in https://github.com/custom-cards/podcast-card/releases/tag/1.0.3
