### ISSUE TITLE
Not working with alexa media player component

### ISSUE THREAD

**Issue by SmartHomeFanatic** [custom-cards/podcast-card#7]
Hi there!
Thanks for that wonderful addon!
I am running the alexa media player custom component. Unfortunately I cannot stream a podcast from the podcast-card on my Alexa's. I think it's rather a problem of the alexa media player component (I read that it needs the content type to be defined correctly) but maybe there is something that can be done on the podcast-card to make it work.

btw: Streaming to a Chromecast works. Perfectly fine.

Thanks again!

**Comment by iantrich** [comment]
I don't have an Alexa device, so not sure how to proceed here 🤷‍♂

**Comment by SmartHomeFanatic** [comment]
Thanks for the quick response! Does this help somehow?
https://github.com/keatontaylor/alexa_media_player/wiki#play-music

**Comment by iantrich** [comment]
I guess I get the idea behind it, but I think that restricts that to apps on the echo device to handle the music, correct? Does the echo have a podcast app?

**Comment by SmartHomeFanatic** [comment]
No it hasn't. That's why I almost freaked out about the possibility to stream podcasts easily to my Alexa's. But I get your point. It really looks like the streaming really works for content that Alexa supports natively.
I think we can close this one :-(
